config/routes.rb
Rails.application.routes.draw do
  resources :booking_days
  resources :searches
  resources :accounting_lists
  resources :accountings
  resources :bookings
  resources :properties
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/homepage'
  get 'pages/manage_property'
  get 'pages/reports'
  get 'pages/streaming_passwords'
  root to: "pages#homepage"
end

app/models/property.rb
class Property < ApplicationRecord
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:nickname, :address, :picture, :bed, :bath, :sq_ft, :notes)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= simple_form_for(@property) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nickname %>
    <%= f.input :address %>
    <%= f.input :picture %>
    <%= f.input :bed %>
    <%= f.input :bath %>
    <%= f.input :sq_ft %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title fw-bold">Properties</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Nickname</th>
            <th>ID</th>
            <th>Address</th>
            <th>Picture</th>
            <th>Bed</th>
            <th>Bath</th>
            <th>Sq ft</th>
            <th>Notes</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @properties.order(:id).each do |property| %>
            <tr>
              <td><%= link_to property.nickname, pages_manage_property_path(property: property.id), class: 'btn btn-sm btn-outline-secondary w100min' %></td>
              <td><%= property.id %></td>
              <td><%= property.address %></td>
              <td><%= property.picture %></td>
              <td><%= property.bed %></td>
              <td><%= property.bath %></td>
              <td><%= property.sq_ft %></td>
              <td><%= property.notes %></td>
              <td><%= link_to 'Show', property %></td>
              <td><%= link_to 'Edit', edit_property_path(property) %></td>
              <td><%= link_to 'Delete', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to 'New Property', new_property_path, class: 'btn btn-sm btn-outline-primary' %>
    </div>
  </div>
</div>

app/views/properties/new.html.erb
<div class="card bg-light" style="width: 30rem;">
  <div class="card-body">
    <h2 class="card-title fw-bold">New Property</h2>

    <%= render 'form', property: @property %>

    <%= link_to 'Back', properties_path %>
  </div>
</div>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @property.nickname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @property.picture %>
</p>

<p>
  <strong>Bed:</strong>
  <%= @property.bed %>
</p>

<p>
  <strong>Bath:</strong>
  <%= @property.bath %>
</p>

<p>
  <strong>Sq ft:</strong>
  <%= @property.sq_ft %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @property.notes %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>