config/routes.rb
Rails.application.routes.draw do
  resources :booking_days
  resources :searches
  resources :accounting_lists
  resources :accountings
  resources :bookings
  resources :properties
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/homepage'
  get 'pages/manage_property'
  get 'pages/reports'
  get 'pages/streaming_passwords'
  root to: "pages#homepage"
end

app/views/pages/homepage.html.erb
  <div class="row">
    <div class="col-4">
      <% @properties.where(id: 1).each do |property| %>
        <div class="card">
          <img src='<%= property.picture %>' class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= property.nickname %></h5>
            <%= link_to 'Manage', pages_manage_property_path(property: property.id), class: "btn btn-primary text-light w150min bg-gradient" %>
          </div>
        </div>
        <br>
      <% end %>
    </div>
    <div class="col-4">
      <% @properties.where(id: 2).each do |property| %>
        <div class="card">
          <img src='<%= property.picture %>' class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= property.nickname %></h5>
            <%= link_to 'Manage', pages_manage_property_path(property: property.id), class: "btn btn-primary text-light w150min bg-gradient" %>
          </div>
        </div>
        <br>
      <% end %>
    </div>
    <div class="col-4">
      <% @properties.where(id: 3).each do |property| %>
        <div class="card">
          <img src='<%= property.picture %>' class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= property.nickname %></h5>
            <%= link_to 'Manage', pages_manage_property_path(property: property.id), class: "btn btn-primary text-light w150min bg-gradient" %>
          </div>
        </div>
        <br>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <% @properties.where(id: 4).each do |property| %>
        <div class="card">
          <img src='<%= property.picture %>' class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= property.nickname %></h5>
            <%= link_to 'Manage', pages_manage_property_path(property: property.id), class: "btn btn-primary text-light w150min bg-gradient" %>
          </div>
        </div>
        <br>
      <% end %>
    </div>
    <div class="col-4">
      <% @properties.where(id: 5).each do |property| %>
        <div class="card">
          <img src='<%= property.picture %>' class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= property.nickname %></h5>
            <%= link_to 'Manage', pages_manage_property_path(property: property.id), class: "btn btn-primary text-light w150min bg-gradient" %>
          </div>
        </div>
        <br>
      <% end %>
    </div>
    <div class="col-4">
      <% @properties.where(id: 6).each do |property| %>
        <div class="card">
          <img src='<%= property.picture %>' class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= property.nickname %></h5>
            <%= link_to 'Manage', pages_manage_property_path(property: property.id), class: "btn btn-primary text-light w150min bg-gradient" %>
          </div>
        </div>
        <br>
      <% end %>
    </div>
  </div>

app/views/pages/manage_property.html.erb
<% property = Property.find_by(id: params['property']) %>

  <h2 class="display-4 fw-bold text-center"><%= property.nickname %></h2>
  <p class="text-center fw-bold"><%= link_to 'Reports', pages_reports_path(property: property.id), class: 'btn btn-sm btn-outline-secondary w100min' %></p>
  <br>
  <div class="row">
    <div class="col-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title fw-bold"><%= link_to 'Revenue', accountings_path(property: params['property'], r_e: 'Revenue') %> <%= link_to 'Add New', new_accounting_path(property: params['property'], type: 'Revenue'), class: 'btn btn-sm btn-outline-primary w100min' %></h5>
          <p><strong><%= link_to (Date.today - 1.year).strftime('%Y'), accountings_path(property: params['property'], r_e: 'Revenue', date_range_a: (Date.today - 1.year).beginning_of_year, date_range_b: (Date.today - 1.year).end_of_year) %>:</strong> <%= number_to_currency(@revenue_previous_year) %></p>
          <p><strong><%= link_to 'YTD', accountings_path(property: params['property'], r_e: 'Revenue', date_range_a: Date.today.beginning_of_year, date_range_b: Date.today.end_of_year) %>:</strong> <%= number_to_currency(@revenue_current_year) %></p>
          <p><strong><%= link_to Date.today.strftime('%B'), accountings_path(property: params['property'], r_e: 'Revenue', date_range_a: Date.today.beginning_of_month, date_range_b: Date.today.end_of_month) %>:</strong> <%= number_to_currency(@revenue_current_month) %></p>
          <p><strong><%= link_to (Date.today - 1.month).strftime('%B'), accountings_path(property: params['property'], r_e: 'Revenue', date_range_a: (Date.today - 1.month).beginning_of_month, date_range_b: (Date.today - 1.month).end_of_month) %>:</strong> <%= number_to_currency(@revenue_previous_month) %></p>
          <table class="table">
            <thead>
              <tr>
                <th>Date</th>
                <th>From</th>
                <th>Payout</th>
              </tr>
            </thead>
            <tbody>
              <% Accounting.where(property_id: params['property']).where(r_e: 'Revenue').order(record_date: :DESC).all.each do |accounting| %>
              <tr>
                <td><%= accounting.record_date.present? ? accounting.record_date.strftime('%-m/%-d/%Y') : '' %></td>
                <td><%= accounting.description %></td>
                <td><%= accounting.amount.present? ? number_to_currency(accounting.amount) : '' %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title fw-bold"><%= link_to 'Expense', accountings_path(property: params['property'], r_e: 'Expense') %> <%= link_to 'Add New', new_accounting_path(property: params['property'], type: 'Expense'), class: 'btn btn-sm btn-outline-primary w100min' %></h5>
          <p><strong><%= link_to (Date.today - 1.year).strftime('%Y'), accountings_path(property: params['property'], r_e: 'Expense', date_range_a: (Date.today - 1.year).beginning_of_year, date_range_b: (Date.today - 1.year).end_of_year) %>:</strong> <%= number_to_currency(@expenses_previous_year) %></p>
          <p><strong><%= link_to 'YTD', accountings_path(property: params['property'], r_e: 'Expense', date_range_a: Date.today.beginning_of_year, date_range_b: Date.today.end_of_year) %>:</strong> <%= number_to_currency(@expenses_current_year) %></p>
          <p><strong><%= link_to Date.today.strftime('%B'), accountings_path(property: params['property'], r_e: 'Expense', date_range_a: Date.today.beginning_of_month, date_range_b: Date.today.end_of_month) %>:</strong> <%= number_to_currency(@expenses_current_month) %></p>
          <p><strong><%= link_to (Date.today - 1.month).strftime('%B'), accountings_path(property: params['property'], r_e: 'Expense', date_range_a: (Date.today - 1.month).beginning_of_month, date_range_b: (Date.today - 1.month).end_of_month) %>:</strong> <%= number_to_currency(@expenses_previous_month) %></p>
          <table class="table">
            <thead>
              <tr>
                <th>Date</th>
                <th>For</th>
                <th>Payment</th>
              </tr>
            </thead>
            <tbody>
              <% Accounting.where(property_id: params['property']).where(r_e: 'Expense').order(record_date: :DESC).all.each do |accounting| %>
              <tr>
                <td><%= accounting.record_date.present? ? accounting.record_date.strftime('%-m/%-d/%Y') : '' %></td>
                <td><%= link_to accounting.description, accountings_path(property: params['property'], description: accounting.description, r_e: 'Expense') %></td>
                <td><%= accounting.amount.present? ? number_to_currency(accounting.amount) : '' %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title fw-bold"><%= link_to 'Bookings', bookings_path(property: params['property']) %> <%= link_to 'Add New', new_booking_path(property: params['property']), class: 'btn btn-sm btn-outline-primary w100min' %></h5>
          <p><strong><%= (Date.today - 1.year).strftime('%Y') %>:</strong> <%= @bookings_previous_year %> bookings | <%= @nights_previous_year %> nights</p>
          <p><strong>YTD:</strong> <%= @bookings_current_year %> bookings | <%= @nights_current_year %> nights</p>
          <p><strong><%= Date.today.strftime('%B') %>:</strong> <%= @bookings_current_month %> bookings | <%= @nights_current_month %> nights</p>
          <p><strong><%= (Date.today - 1.month).strftime('%B') %>:</strong> <%= @bookings_previous_month %> bookings | <%= @nights_previous_month %> nights</p>
          <table class="table">
            <thead>
              <tr>
                <th>Checkin</th>
                <th>Nights</th>
                <th>Payment</th>
              </tr>
            </thead>
            <tbody>
              <% Booking.where(property_id: params['property']).order(check_in: :DESC).all.each do |booking| %>
              <tr>
                <td><%= booking.check_in.present? ? booking.check_in.strftime('%-m/%-d/%Y') : '' %></td>
                <td><%= booking.nights %></td>
                <td><%= booking.payout.present? ? number_to_currency(booking.payout) : '' %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>

  <br><br>

app/views/pages/streaming_passwords.html.erb
<h2 class="display-6 fw-bold text-center">Streaming Accounts</h2>
<br>
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title fw-bold"></h5>
        <table class="table">
          <!-- <thead>
            <tr>
              <th>App</th>
              <th>Username</th>
              <th>Password</th>
            </tr>
          </thead> -->
          <tbody>
            <% if params['property'].present? %>
              <tr>
                <td class="fw-bold">Spotify</td>
                <% if params['property'] == '1' %>
                  <td>54487Tanglewood@gmail.com <br><strong>pw:</strong> PK7Kj6yH</td>
                <% elsif params['property'] == '2' %>
                <td>78200Cortez@gmail.com <br><strong>pw:</strong> 4z976r5n</td>
                <% elsif params['property'] == '3' %>
                  <td>530Kst212@gmail.com <br><strong>pw:</strong> a6w2hapf</td>
                <% elsif params['property'] == '4' %>
                  <td>1205Pacific@gmail.com <br><strong>pw:</strong> a8umbd8p</td>
                <% end %>
              </tr>
            <% end %>
            <tr>
              <td class="fw-bold">ESPN+</td>
              <td>nash.property1@gmail.com <br><strong>pw:</strong> j6z96l</td>
            </tr>
            <tr>
              <td class="fw-bold">Disney+</td>
              <td>nash.property1@gmail.com<br><strong>pw:</strong> j6z96l</td>
            </tr>
            <tr>
              <td class="fw-bold">Hulu</td>
              <td>nash.property1@gmail.com<br><strong>pw:</strong> j6z96l</td>
            </tr>
            <tr>
              <td class="fw-bold">HBO Max</td>
              <td>nash.property1@gmail.com<br><strong>pw:</strong> k3j8unc6</td>
            </tr>
            <tr>
              <td class="fw-bold">Paramount+</td>
              <td>nash.property1@gmail.com<br><strong>pw:</strong> f419jx</td>
            </tr>
            <tr>
              <td class="fw-bold">Peacock</td>
              <td>nash.property1@gmail.com<br><strong>pw:</strong> tmgx7fv74n</td>
            </tr>
            <tr>
              <td class="fw-bold">Apple TV+</td>
              <td>nash.property1@gmail.com<br><strong>pw:</strong> eqNaT3Sb</td>
            </tr>
            <tr>
              <td class="fw-bold">Netflix</td>
              <td>nash.property1@gmail.com<br><strong>pw:</strong> r8ufgx</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>