config/routes.rb
Rails.application.routes.draw do
  resources :booking_days
  resources :searches
  resources :accounting_lists
  resources :accountings
  resources :bookings
  resources :properties
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/homepage'
  get 'pages/manage_property'
  get 'pages/reports'
  get 'pages/streaming_passwords'
  root to: "pages#homepage"
end

app/models/accounting.rb
class Accounting < ApplicationRecord
end

app/controllers/accountings_controller.rb
class AccountingsController < ApplicationController
  before_action :set_accounting, only: %i[ show edit update destroy ]

  # GET /accountings or /accountings.json
  def index
    @search = Search.new

# All Possible Criterias 
    params['property'].present? ? property = params['property'] : property = 1..100
    params['description'].present? ? description = params['description'] : description = AccountingList.pluck(:accounting_type)
    params['r_e'].present? ? r_e = params['r_e'] : r_e = ['Revenue', 'Expense']
    params['date_range_a'].present? ? date_range_a = params['date_range_a'] : date_range_a = '2000-01-01'
    params['date_range_b'].present? ? date_range_b = params['date_range_b'] : date_range_b = '2150-01-01'

    @accountings = Accounting.where(property_id: property).where(description: description).where(r_e: r_e).where(record_date: date_range_a .. date_range_b).order(record_date: :DESC).all
    @accountings_sum = @accountings.sum(:amount)
    @accountings_count = @accountings.count
  end

  # GET /accountings/1 or /accountings/1.json
  def show
  end

  # GET /accountings/new
  def new
    @accounting = Accounting.new
  end

  # GET /accountings/1/edit
  def edit
  end

  # POST /accountings or /accountings.json
  def create
    @accounting = Accounting.new(accounting_params)

    respond_to do |format|
      if @accounting.save
        # redirect_to pages_manage_property_path(property: @accounting.id)
        format.html { redirect_to pages_manage_property_path(property: @accounting.property_id), notice: "Accounting was successfully created." }
        format.json { render :show, status: :created, location: @accounting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @accounting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accountings/1 or /accountings/1.json
  def update
    respond_to do |format|
      if @accounting.update(accounting_params)
        format.html { redirect_to accounting_url(@accounting), notice: "Accounting was successfully updated." }
        format.json { render :show, status: :ok, location: @accounting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @accounting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accountings/1 or /accountings/1.json
  def destroy
    @accounting.destroy

    respond_to do |format|
      format.html { redirect_to accountings_url, notice: "Accounting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting
      @accounting = Accounting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def accounting_params
      params.require(:accounting).permit(:property_id, :r_e, :description, :amount, :notes, :record_date)
    end
end

app/helpers/accountings_helper.rb
module AccountingsHelper
end

app/views/accountings/_form.html.erb
<%= simple_form_for(@accounting) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <!-- Property ID - IF New then hide and take from the Params - If edit display field -->
    <% if @accounting.property_id.blank? %>
      <%= f.input :property_id, input_html: { value: params['property'] }, as: :hidden%>
    <% else %>
      <%= f.input :property_id %>
      <br>
    <% end %>
    <!-- Revenue/Expense ID - IF New then hide and take from the Params - If edit display field -->
    <% if @accounting.r_e.blank? %>
      <%= f.input :r_e, input_html: { value: params['type'] }, as: :hidden%>
    <% else %>
      <%= f.input :r_e, label: 'Revenue/Expense' %>
      <br>
    <% end %>

    <%= f.input :record_date %>
    <br>
    <% if params['type'] == 'Revenue' %>
      <%= f.input :description, label: 'Source', as: :select, collection: ['Airbnb', 'Other']%>
    <% elsif params['type'] == 'Expense' %>
      <%= f.input :description, as: :select, collection: AccountingList.pluck(:accounting_type) %>
    <% else %>
        <%= f.input :description %>
    <% end %>
    <br>
    <%= f.input :amount %>
    <br>
    <%= f.input :notes %>
  </div>
<br>
  <div class="form-actions">
    <%= f.button :submit, 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/accountings/_search_form.html.erb
<%= simple_form_for(@search) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-2">
        <% if params['property'].present? %>
            <% property = Property.where(id: params['property']).pluck(:nickname)[0] %>
            <%= f.input :property, as: :select, collection: Property.pluck(:nickname), selected: property %>
        <% else %>
            <%= f.input :property, as: :select, collection: Property.pluck(:nickname) %>
        <% end %>
      </div>
      <div class="col-2">
        <% if params['r_e'].present? %>
          <%= f.input :accounting_type, as: :select, collection: ['Revenue', 'Expense'], selected: params['r_e'] %>
        <% else %>
          <%= f.input :accounting_type, as: :select, collection: ['Revenue', 'Expense'] %>
        <% end %>
      </div>
      <div class="col-2">
        <% if params['description'].present? %>
          <%= f.input :description, as: :select, collection: AccountingList.pluck(:accounting_type), selected: params['description'] %>
        <% else %>
          <%= f.input :description, as: :select, collection: AccountingList.pluck(:accounting_type) %>
        <% end %>
      </div>
      <div class="col-3">
        <%= f.input :date_range_a, label: 'Date Range Start', include_blank: true %>
      </div>
      <div class="col-3">
        <%= f.input :date_range_b, label: 'Date Range End', include_blank: true %>
      </div>
    </div>
    <%#= f.input :field_1 %>
    <%#= f.input :field_2 %>
    <%#= f.input :field_3 %>
  </div>
  <br>
  <div class="row">
    <div class="col-1">
      <div class="form-actions">
        <%= f.button :submit, 'Search', class: 'btn btn-primary btn-gradient' %>
      </div>
    </div>
  </div>
<% end %>

app/views/accountings/edit.html.erb
<div class="card bg-light" style="width: 30rem;">
  <div class="card-body">
    <h4 class="card-title">Editing Accounting</h4>
    <%= render 'form', accounting: @accounting %>
    <br>
    <%= link_to 'Show', @accounting %> |
    <%= link_to 'Back', accountings_path %>
  </div>
</div>

app/views/accountings/index.html.erb
<p id="notice"><%= notice %></p>
  <p>
    <a class="" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      Search
    </a>
  </p>
  <p>
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
      <%= render 'search_form', search: @search %>
    </div>
  </div>
  </p>

  <p><%= @description %></p>


  <div class="card">
    <div class="card-body">
      <h2 class="card-title fw-bold">Accountings</h2>
      <% if params['property'].present? %>
        <% property = Property.find_by(id: params['property']) %>
        <p><small><strong>Property:</strong> <%= property.nickname %></small></p>
      <% end %>
      <% if params['description'].present? %>
        <p><small><strong>Description:</strong> <%= params['description'] %></small></p>
      <% end %>
      <table class="table">
        <thead>
          <tr>
            <th>Property</th>
            <th>Date</th>
            <th>Revenue/Expense</th>
            <th>Description</th>
            <th>Amount</th>
            <th>Notes</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @accountings.each do |accounting| %>
            <tr>
              <% property = Property.find_by(id: accounting.property_id) %>
              <td><%= accounting.property_id.present? ? property.nickname : ''%></td>
              <td><%= accounting.record_date.present? ? accounting.record_date.strftime('%-m/%-d/%Y') : ''%></td>
              <td><%= accounting.r_e %></td>
              <td><%= accounting.description %></td>
              <td><%= number_to_currency(accounting.amount) %></td>
              <td><%= accounting.notes %></td>
              <td><%= link_to 'Show', accounting %></td>
              <td><%= link_to 'Edit', edit_accounting_path(accounting) %></td>
              <td><%= link_to 'Delete', accounting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
          <tr class="fw-bold">
            <td>Totals</td>
            <td><%= @accountings_count %></td>
            <td colspan="2"></td>
            <td><%= number_to_currency(@accountings_sum) %></td>
            <td colspan="4"></td>
          </tr>
        </tbody>
      </table>

      <%#= link_to 'New Accounting', new_accounting_path %>
      </div>
  </div>



  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

app/views/accountings/new.html.erb
<div class="card bg-light" style="width: 30rem;">
  <div class="card-body">
    <h4 class="card-title">Add <%= params['type'] %></h4>
    <%= render 'form', accounting: @accounting %>
  </div>
</div>

<%#= link_to 'Back', accountings_path %>

app/views/accountings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @accounting.property_id %>
</p>

<p>
  <!-- <strong>R e:</strong> -->
  <strong>Type:</strong>
  <%= @accounting.r_e %>
</p>

<p>
  <strong>Description:</strong>
  <%= @accounting.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@accounting.amount) %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @accounting.notes %>
</p>

<%= link_to 'Edit', edit_accounting_path(@accounting) %> |
<%= link_to 'Back', accountings_path %>