config/routes.rb
Rails.application.routes.draw do
  resources :booking_days
  resources :searches
  resources :accounting_lists
  resources :accountings
  resources :bookings
  resources :properties
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/homepage'
  get 'pages/manage_property'
  get 'pages/reports'
  get 'pages/streaming_passwords'
  root to: "pages#homepage"
end

app/models/booking_day.rb
class BookingDay < ApplicationRecord
end

app/controllers/booking_days_controller.rb
class BookingDaysController < ApplicationController
  before_action :set_booking_day, only: %i[ show edit update destroy ]

  # GET /booking_days or /booking_days.json
  def index
    @booking_days = BookingDay.all
  end

  # GET /booking_days/1 or /booking_days/1.json
  def show
  end

  # GET /booking_days/new
  def new
    @booking_day = BookingDay.new
  end

  # GET /booking_days/1/edit
  def edit
  end

  # POST /booking_days or /booking_days.json
  def create
    @booking_day = BookingDay.new(booking_day_params)

    respond_to do |format|
      if @booking_day.save
        format.html { redirect_to booking_day_url(@booking_day), notice: "Booking day was successfully created." }
        format.json { render :show, status: :created, location: @booking_day }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booking_days/1 or /booking_days/1.json
  def update
    respond_to do |format|
      if @booking_day.update(booking_day_params)
        format.html { redirect_to booking_day_url(@booking_day), notice: "Booking day was successfully updated." }
        format.json { render :show, status: :ok, location: @booking_day }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_days/1 or /booking_days/1.json
  def destroy
    @booking_day.destroy

    respond_to do |format|
      format.html { redirect_to booking_days_url, notice: "Booking day was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking_day
      @booking_day = BookingDay.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_day_params
      params.require(:booking_day).permit(:day, :property_id, :day_rate, :extra_s, :extra_i, :extra_b)
    end
end

app/helpers/booking_days_helper.rb
module BookingDaysHelper
end

app/views/booking_days/_form.html.erb
<%= simple_form_for(@booking_day) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :day %>
    <%= f.input :property_id %>
    <%= f.input :day_rate %>
    <%= f.input :extra_s %>
    <%= f.input :extra_i %>
    <%= f.input :extra_b %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/booking_days/edit.html.erb
<h1>Editing Booking Day</h1>

<%= render 'form', booking_day: @booking_day %>

<%= link_to 'Show', @booking_day %> |
<%= link_to 'Back', booking_days_path %>

app/views/booking_days/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-body">
    <h2 class="card-title fw-bold">Booking Days</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Day</th>
          <th>Property</th>
          <th>Day rate</th>
          <!-- <th>Extra s</th> -->
          <!-- <th>Extra i</th> -->
          <!-- <th>Extra b</th> -->
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @booking_days.each do |booking_day| %>
          <tr>
            <td><%= booking_day.day %></td>
            <td><%= booking_day.property_id %></td>
            <td><%= booking_day.day_rate %></td>
            <!-- <td><%#= booking_day.extra_s %></td> -->
            <!-- <td><%#= booking_day.extra_i %></td> -->
            <!-- <td><%#= booking_day.extra_b %></td> -->
            <td><%= link_to 'Show', booking_day %></td>
            <td><%= link_to 'Edit', edit_booking_day_path(booking_day) %></td>
            <td><%= link_to 'Destroy', booking_day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<%= link_to 'Add New', new_booking_day_path %>

app/views/booking_days/new.html.erb
<h1>New Booking Day</h1>

<%= render 'form', booking_day: @booking_day %>

<%= link_to 'Back', booking_days_path %>

app/views/booking_days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @booking_day.day %>
</p>

<p>
  <strong>Property:</strong>
  <%= @booking_day.property_id %>
</p>

<p>
  <strong>Day rate:</strong>
  <%= @booking_day.day_rate %>
</p>

<p>
  <strong>Extra s:</strong>
  <%= @booking_day.extra_s %>
</p>

<p>
  <strong>Extra i:</strong>
  <%= @booking_day.extra_i %>
</p>

<p>
  <strong>Extra b:</strong>
  <%= @booking_day.extra_b %>
</p>

<%= link_to 'Edit', edit_booking_day_path(@booking_day) %> |
<%= link_to 'Back', booking_days_path %>